<?php


//Implements hook_block_info
function quotator_block_info() {
	$block['myquote'] = array(
		'info' => t('A Quote rotator.'),
		'cache' => DRUPAL_CACHE_PER_ROLE,
	);

	return $block;
}

//Implements hook_block_view
function quotator_block_view($delta) {

	$block = array();
	if($delta == 'myquote'){
		$quote = variable_get('q');
		$author = variable_get('a');
		$values = array('@quote' => $quote, '@author' => $author);
		$block['subject'] = t('Quote of the Day');
		$block['content'] = t('@quote, @author', $values);
	}
	return $block;
}

/**function drupalmodule_block_configure($delta) {
$form = array;
switch ($delta) {
case 'Quotable':
$default_text = '';
$form['quotation1'] = array(
'#type' => 'textfield',
‎ '#title' => t('Quotation 1'),
'#description' => t('Enter the text of your first quote.'),
'#size' => 100,
'#maxlength' => 200,
'#default_value' => variable_get('mei_core_quotable-quote1', $default_text),
'#required' => TRUE,
);


default:
break;
}
return $form;
}*/


//Implements hook_block_configure
function quotator_block_configure($delta) {
	$form = array();
	switch($delta){
		case 'myquote':
			$form['quotable'] = array(
				'#type' => 'fieldset',
				'#title' => t('Quotable'),
				'#tree' => TRUE,
				'#collapsible' => FALSE,

				$form['quotable']['quote'] = array(
					'#type' => 'textfield',
					'#title' => t('Quote'),
					'#description' => t('Enter your quote.'),
					'#size' => 100,
					'#maxlength' => 200,
					'#default_value' => variable_get('q'),
				),
				$form['quotable']['author'] = array(
					'#type' => 'textfield',
					'#title' => t('Attribution'),
					'#description' => t('Enter your attribution.'),
					'#size' => 100,
					'#maxlength' => 200,
					'#default_value' => variable_get('a'),
				),
				
			);
		default:
			break;
	}
	return $form;
}

//Implements hook_block_save()

function quotator_block_save($delta, $edit = array()) {
	if($delta == 'myquote'){
		variable_set('q', $edit['quotable']['quote']);
		variable_set('a', $edit['quotable']['author']);
	}
}



//	variable_set('deep_thoughts', $edit['quotable']['q']);
//	variable_set('author', $edit['quotable']['a']);
//}





